name: Yii2 Dashboard
project: cornernote/yii2-dashboard
description: Create and manage dashboards using custom layouts and panels.
screenshot: https://cloud.githubusercontent.com/assets/51875/8636670/21febed6-28ae-11e5-8fc7-dc57e5bbc422.png

markdown: redcarpet
highlighter: pygments
permalink: /:title/
exclude: ["README.md"]
baseurl: /yii2-dashboard